[features]
seeds = false
skip-lint = false
[programs.localnet]
sell_nft = "HgdZU356qBiVDeNrEsuSbyQ4wGvYdUdhVJpirAFzaPtf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rishabhvasudevan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
